services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    networks:
      - internal
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5000:5432"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    volumes:
      - "/home/foxtrot/development/docker/db_volumes/patient-service-db:/var/lib/postgresql/data"
    networks:
      - internal

  patient-service:
    build:
      context: ./patient-service
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SQL_INIT_MODE: never
    networks:
      - internal

  billing-service:
    build:
      context: ./billing-service
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    depends_on:
      - patient-service
    networks:
      - internal

  analytics-service:
    build:
      context: ./analytics-service
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "4002:4002"
    depends_on:
      - billing-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      - analytics-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    networks:
      - internal

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    ports:
      - "5001:5432"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    volumes:
      - "/home/foxtrot/development/docker/db_volumes/auth-service-db:/var/lib/postgresql/data"
    networks:
      - internal

  auth-service:
    build:
      context: ./auth-service
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "4005:4005"
    depends_on:
      - auth-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: never
      JWT_SECRET: RH0oN2leRU45SEd0PyJoRnRpdHk1Skh7Uk9BT0YhcTkhV3wtWTZOMDokLz5nOCc4PEV0OE0/PkV5Z0c2dWMm
    networks:
      - internal

#volumes:
#  patient_service_db_data:
#    driver: local
#  auth_service_db_data:
#    driver: local

networks:
  internal:
    driver: bridge
